# Generated by Django 5.2.13 on 2026-04-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('image', models.ImageField(upload_to='blog_images/%Y/%m/%d')),
                ('image_alt', models.CharField(blank=True, max_length=250, verbose_name='descrição da imagem')),
                ('image_caption', models.CharField(max_length=250, verbose_name='legenda da imagem')),
            ],
        ),
    ]
