# Generated by Django 6.0.3 on 2026-04-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_alt',
            field=models.CharField(default=0, max_length=250, verbose_name='descrição da imagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_caption',
            field=models.CharField(blank=True, max_length=250, verbose_name='legenda da imagem'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Titulo'),
        ),
    ]
