# Generated by Django 6.0.3 on 2026-04-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0002_blogpost_image_alt_alter_blogpost_image_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titulo'),
        ),
    ]
