# Generated by Django 6.0.3 on 2026-04-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0003_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_images/%Y/%m/%d'),
        ),
    ]
