# Generated by Django 6.0.4 on 2026-04-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0004_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blog_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_alt',
            field=models.CharField(blank=True, max_length=250, verbose_name='descrição da imagem'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_caption',
            field=models.CharField(max_length=250, verbose_name='legenda da imagem'),
        ),
    ]
