# Generated by Django 5.2.12 on 2026-04-04 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('adulto', models.PositiveIntegerField(default=1)),
                ('crianca', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.hospedes')),
            ],
        ),
    ]
