# Generated by Django 5.2.12 on 2026-04-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('adulto', models.PositiveIntegerField(default=1)),
                ('crianca', models.PositiveIntegerField(default=0)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('quarto', models.TextField()),
                ('rest_dia', models.DateField()),
                ('rest_hora', models.TimeField()),
            ],
        ),
    ]
