# Generated by Django 6.0.4 on 2026-04-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedes',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
