# Generated by Django 5.2.12 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedes',
            name='celular',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospedes',
            name='email',
            field=models.EmailField(default='', max_length=200, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
